services:

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "5400:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge

volumes:
  postgres_data: