# PostgreSQL configuration for all environments
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: <%= ENV['DOCKERENV'] ? 'postgres' : 'localhost' %>
  username: postgres
  password: postgres
  database: postgres

test:
  <<: *default
  host: <%= ENV['DOCKERENV'] ? 'postgres' : 'localhost' %>
  username: postgres
  password: postgres
  database: postgres

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] || 'postgres' %>
